---
kind: pipeline
type: kubernetes
name: Test

platform:
  os: linux
  arch: arm

steps:
  - name: unit-test
    image: golang:1.15-stretch
    commands:
      - apt-get update
      - apt-get install -y git build-essential
      - go test -coverprofile cover.out ./...
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

  - name: coverage
    image: golang:1.15-stretch
    commands:
      - go tool cover -func cover.out
    depends_on:
      - unit-test

---
kind: pipeline
type: kubernetes
name: Image Staging

depends_on:
- Test

platform:
  os: linux
  arch: arm

steps:
  - name: build-test-consumer
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gonyexpress-consumer
      build_args: TARGET=consumer
      tags: ${DRONE_BRANCH},unstable
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

  - name: build-test-producer
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gonyexpress-producer
      build_args: TARGET=producer
      tags: ${DRONE_BRANCH},unstable
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

---
kind: pipeline
type: kubernetes
name: Image Production

trigger:
  event:
    - tag

depends_on:
- Image Staging

platform:
  os: linux
  arch: arm

steps:
  - name: build-production-consumer
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gonyexpress-consumer
      build_args: TARGET=consumer
      auto_tag: true
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

  - name: build-production-producer
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: gonyexpress-consumer
      build_args: TARGET=producer
      auto_tag: true
      cache: true
      insecure_registry: true
    resources:
      limits:
        cpu: 1000
        memory: 500MiB

---
kind: signature
hmac: 280938c5f4b3a91ca3e4644743ffa12ea40db3532753051eda06c313b3f9948c

...
